apiVersion: v1
kind: Service
metadata:
  name: ginaccounting-service
spec:
  ports:
  - port: 30080
    nodePort: 30080
    targetPort: ginacn-port
    protocol: TCP
  selector:
    app: ginacn
  type: NodePort
