FROM centos:latest
RUN yum update -y
RUN yum install wget -y
RUN yum install git-core -y
RUN wget https://dl.google.com/go/go1.9.3.linux-amd64.tar.gz
RUN tar -xzf go1.9.3.linux-amd64.tar.gz
RUN mv go /usr/local
ENV GOROOT /usr/local/go
RUN mkdir $HOME/go
RUN mkdir $HOME/go/ginAccounting
ENV GOPATH $HOME/go
ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH
RUN go version
RUN go env
COPY . /root/go/ginAccounting/
RUN yum install net-tools -y
RUN go get "github.com/gin-gonic/gin"
RUN go get "gopkg.in/mgo.v2"
WORKDIR /root/go/ginAccounting
RUN go build
ENV CONTAINERIZED true
EXPOSE 8080
